<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("employees", "Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit employees
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "employees/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMiddleName" class="col-sm-2 control-label">Middle Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("middle_name", "size" => 30, "class" => "form-control", "id" => "fieldMiddleName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastName" class="col-sm-2 control-label">Last Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("last_name", "size" => 30, "class" => "form-control", "id" => "fieldLastName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPost" class="col-sm-2 control-label">Post</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("post", "size" => 30, "class" => "form-control", "id" => "fieldPost")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRoot" class="col-sm-2 control-label">Root</label>
    <div class="col-sm-10">
        <?php echo $this->tag->selectStatic(array("root", Employees::root_list(), "class" => "form-control", "id" => "fieldRoot")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("email", "size" => 30, "class" => "form-control", "id" => "fieldEmail")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPhone" class="col-sm-2 control-label">Phone</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("phone", "size" => 30, "class" => "form-control", "id" => "fieldPhone")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldHomePhone" class="col-sm-2 control-label">Home Of Phone</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("home_phone", "size" => 30, "class" => "form-control", "id" => "fieldHomePhone")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("description", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDescription")) ?>
    </div>
</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
