<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("employees/index", "Go Back")); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(array("employees/new", "Create ")); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Name</th>
            <th>Middle Of Name</th>
            <th>Last Of Name</th>
            <th>Post</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Home Of Phone</th>
            <th>Description</th>
            <th>Root</th>
            <!-- <th>Lft</th>
            <th>Rgt</th>
            <th>Level</th> -->

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $employee): ?>
            <tr>
                <td><?php echo $employee->id ?></td>
            <td><?php echo $employee->name ?></td>
            <td><?php echo $employee->middle_name ?></td>
            <td><?php echo $employee->last_name ?></td>
            <td><?php echo $employee->post ?></td>
            <td><?php echo $employee->email ?></td>
            <td><?php echo $employee->phone ?></td>
            <td><?php echo $employee->home_phone ?></td>
            <td><?php echo $employee->description ?></td>
            <td><?php echo ((is_object($employee->getRelated('root_name')) and $employee->root != 1 )?$employee->getRelated('root_name')->name:'') ?></td>
            <!-- <td><?php echo $employee->lft ?></td>
            <td><?php echo $employee->rgt ?></td>
            <td><?php echo $employee->level ?></td> -->

                <td><?php echo $this->tag->linkTo(array("employees/edit/" . $employee->id, "Edit")); ?></td>
                <td><?php echo $this->tag->linkTo(array("employees/delete/" . $employee->id, "Delete")); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("employees/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("employees/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("employees/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("employees/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
