<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(array("categories", "Back")) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit categories
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        array(
            "categories/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        )
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("name", "size" => 30, "class" => "form-control", "id" => "fieldName")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(array("description", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldDescription")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRoot" class="col-sm-2 control-label">Root</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("root", "type" => "number", "class" => "form-control", "id" => "fieldRoot")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLft" class="col-sm-2 control-label">Lft</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("lft", "type" => "number", "class" => "form-control", "id" => "fieldLft")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRgt" class="col-sm-2 control-label">Rgt</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("rgt", "type" => "number", "class" => "form-control", "id" => "fieldRgt")) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLevel" class="col-sm-2 control-label">Level</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(array("level", "type" => "number", "class" => "form-control", "id" => "fieldLevel")) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-default")) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
